<body>
<div class="container" id="formContainer">
    <div class="c" id="logInText">Log in to be able to make reservations! </div>
    <div class="col-lg-4 col-md-4 col-md-offset-4 col-lg-offset-4 well" id="main">
        <form method="post" action="/users/logIn">
            <div class="form-group">
                <input type="email" class="form-control" name = "user" id="unameTxt" placeholder="Username" required autofocus>
            </div>
            <div class="form-group">
                <input type="password" class="form-control" name= "password" id="passTxt" placeholder="Password" required/>
            </div>
            <div class="form-group text-center">
                <button type="submit" name="button" class="btn btn-success">Sign In</button>
                <a class="btn btn-primary" href="/users/register">Sign Up</a>
            </div>
        </form>
        <div class="error"><?php echo $error?></div>
    </div>
</div>
</body>