<body>
<div class="container" id="formContainer">
    <div class="c" id="logInText">Register to be able to make reservations! </div>
    <div class="col-lg-4 col-md-4 col-md-offset-4 col-lg-offset-4 well" id="main">
        <form method="post" action="/users/register">
            <div class="form-group">
                <input type="email" name = "user" class="form-control" id="unameTxt" placeholder="Username" required autofocus>
            </div>
            <div class="form-group">
                <input type="password" name ="password" class="form-control" id="passTxt" placeholder="Password" required/>
            </div>
            <div class="form-group">
                <input type="password" name= "repeatPassword" class="form-control" id="rpassTxt" placeholder="Repeat Password" required/>
            </div>
            <div class="form-group text-center">
                <button type="submit" name="button" class="btn btn-success">Register</button>
            </div>
        </form>
        <div class="error"><?php echo $error?></div>
    </div>
</div>

</body>